version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123   
      MYSQL_DATABASE: Sharks             
      MYSQL_USER: admin                  
      MYSQL_PASSWORD: student1234        
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  tomcat:
    image: tomcat:latest
    container_name: tomcat
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./ROOT:/usr/local/tomcat/webapps/ROOT   
      - ./ROOT/WEB-INF/lib:/usr/local/tomcat/webapps/ROOT/WEB-INF/lib
    depends_on:
      - mysql

  apache:
    image: apache:latest
    container_name: apache
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./ROOT/userupload:/usr/local/apache2/htdocs/userupload   
